
workflow:

on: pull_request

jobs:
  echo:
    runs-on: ubuntu-latest
    steps: #fazer standart execution para caso não passe em username, pasword e chave ssh bloquear
      # Login
      - name: secret username
        run: echo ${{ secrets.DOCKER_USERNAME}}
      - name: secret password
        run: echo ${{secrets.DOCKER_PASSWORD}}
      - name: secret ssh key
        run: echo ${{secrets.SSH_PRIVATE_KEY}}
        uses:
      # acesso ao repositorio
      - name: repository
        uses: actions/checkout@v4
        with:
          repository: seu-usuario/hello-manifests
          token: ${{ secrets.GITHUB_TOKEN }}
          path: manifests
      - name: Update Deployment Image
        run: |
          NEW_TAG=${{ github.sha }}
          # Exemplo de comando sed para substituir a tag da imagem no deployment.yaml
          sed -i "s|image: .*/hello-app:.*|image: ${{ secrets.DOCKER_USERNAME }}/hello-app:${NEW_TAG}|" manifests/deployment.yaml
          
      # 6. Commit e Push para o repositório de manifestos
      - name: Commit and Push Manifests Update
        run: |
          cd manifests
          git config user.name "GitHub Actions Bot"
          git config user.email "actions-bot@users.noreply.github.com"
          git add deployment.yaml
          git commit -m "feat(ci): New image tag ${{ github.sha }}" || echo "No changes to commit"
          git push
